In [1]:
import numpy as np
from pyzx.linalg import Mat2

In [2]:
A = [[1, 0, 1],
     [0, 0, 1]]
B = [0, 0, 1]

In [3]:
np.linalg.pinv(A)

array([[ 1., -1.],
       [ 0.,  0.],
       [-0.,  1.]])

In [4]:
np.linalg.pinv(A).transpose().dot(B)

array([-0.,  1.])

In [42]:
a = np.array([[1,1],
              [0,1],
              [1,0]], dtype=int)
b = np.array([[0],[1],[1]], dtype=int)

In [6]:
at = a.transpose()
ata = at.dot(a)%2
ata_inv = np.array(Mat2(ata).inverse().data)
atb = at.dot(b)%2
X = ata_inv.dot(atb)%2
print(X)

[1 1]


In [26]:
a.transpose().dot(a)%2

array([[1, 1],
       [1, 0]])

In [8]:
np.linalg.pinv(a)

array([[ 0.33333333, -0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667, -0.33333333]])

In [9]:
np.linalg.pinv(a).dot(b)

array([0.33333333, 0.33333333])

In [44]:
MatA = Mat2(a)
MatB = Mat2(b)
MatA

[ 1  1 ]
[ 0  1 ]
[ 1  0 ]

In [45]:
MatA.gauss(full_reduce=True, x=MatB)
MatB

[ 1 ]
[ 1 ]
[ 0 ]

In [57]:
MatA.data.transpose().dot(MatB.data).flatten()

array([1, 1])

In [61]:
l = [1,3,2,0]
l.sort()

In [62]:
l

[0, 1, 2, 3]

In [64]:
[10, 11] + l

[10, 11, 0, 1, 2, 3]

In [65]:
l

[0, 1, 2, 3]

In [66]:
l.pop()

3

In [67]:
l

[0, 1, 2]